# Generated by Django 5.0.14 on 2026-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
